services:
  db:
    image: postgres:15
    container_name: case_db
    restart: always
    environment:
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: case_dev
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
